### ISSUE TITLE
Wrong entry point in v2.2.1

### ISSUE THREAD

**Issue by masontikhonov** [christiangalsterer/mongodb-driver-prometheus-exporter#132]
## Overview
`package.json` specifies entry point as `dist/index.js`; while real entry point in version 2.2.1 is `dist/src/index.js`.

This blocks usage of the package since Node.js cannot resolve package.

## Expected behavior
`"main"` field of `package.json` should consider structure of the build code.

**Comment by christiangalsterer** [comment]
Thanks for spotting this. This was introduced with recent changes in es-config-love which required a change in the whole tsconfig configuration and then this issue got unfortunately introduced.

**Comment by christiangalsterer** [comment]
Thanks for providing a fix, but I used a different approach where no extra tsconfig is necessary. v2.2.2 is now available

**Comment by masontikhonov** [comment]
Thanks for releasing a fix! 🙌
