### ISSUE TITLE
Add metric name prefix to driver options

### ISSUE THREAD

**Issue by Klem3n** [christiangalsterer/mongodb-driver-prometheus-exporter#56]
It would be very useful if we could add a prefix to metric names.

Example:

options.prefix = 'service1_'

// All metrics would have service1_ prefix added before the name
console.log(exporter.poolSize.name); // Would return service1_mongodb_driver_pool_size

**Comment by christiangalsterer** [comment]
Thanks for creating the issue and the related pull request. Before merging can you provide a little more context about the use case for this. Given your example with the service as the prefix I'm wondering if this is really the way to go. Typically and best practice in the prometheus ecosystem is to differentiate between different services/applications using a label and not a prefix on a metric name.

**Comment by Klem3n** [comment]
Sure! prom-client library also allows you to set a prefix for the default metrics:

client.collectDefaultMetrics({
    prefix: 'service_'
});

I understand it is a better practice to separate services by labels, but sometimes separate services on Grafana with different dashboar

**Comment by christiangalsterer** [comment]
A new release 2.1.0 is now available. Thanks again for your contribution.
